### ISSUE TITLE
hello，I would like to know what is the version of Pytorch Lightning

### ISSUE THREAD

**Issue by Yunx1aoyuj1** [Graph-Machine-Learning-Group/spin#1]
I'm running into a debug while working on this code. if the full environment is available, it will help a lot.

**Comment by 1664587146** [comment]
I'm running into a debug while working on this code. if the full environment is available, it will help a lot.

**Comment by marshka** [comment]
Hi, the version used in our experiment is the 1.5.10 (newer versions should work as well)

**Comment by Yunx1aoyuj1** [comment]
I tried the newer version(the version is 1.7.7). But the program can`t run in any datasets. When I change it to your version, the code runs well.
