### ISSUE TITLE
BUG: TypeError: on_train_batch_start() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by guo-huojian** [Graph-Machine-Learning-Group/spin#10]
File "/home/yu/anaconda3/envs/spin/lib/python3.8/site-packages/tsl/imputers/imputer.py", line 134, in on_train_batch_start
        super(Imputer, self).on_train_batch_start(batch, batch_idx, unused)
TypeError: on_train_batch_start() takes 3 positional arguments but 4 were given

**Comment by marshka** [comment]
Hi, this issue is caused by a change in pytorch lightning's API. Please see #4.
