### ISSUE TITLE
How to run on other traffic dataset?

### ISSUE THREAD

**Issue by JeremyChou28** [Graph-Machine-Learning-Group/spin#12]
Hello, may I ask how the spin code runs on other spatio-temporal datasets? 
Can you provide a case code? 
Thank you.

**Comment by marshka** [comment]
Hi, I'm not sure I got the question. However, consider that now SPIN is part of torch spatiotemporal (https://github.com/TorchSpatiotemporal/tsl/blob/7bc1a6894d164ee39430383788316cf0912886cb/tsl/nn/models/stgn/spin_model.py), a library for STGNNs that comes with a rich set of datasets that can be used.
