### ISSUE TITLE
StaticGraphEmbedding

### ISSUE THREAD

**Issue by chenxiaodanhit** [Graph-Machine-Learning-Group/spin#3]
Thank you for your contributions. I am confusing about the function of StaticGraphEmbedding, and I do not find the implementation of this function. May be I ignore some what or where can I find this function? Thank you for your help!

**Comment by marshka** [comment]
Hi, here you have the code for this class:

https://github.com/TorchSpatiotemporal/tsl/blob/main/tsl/nn/base/embedding.py

In practice, this object provides an identifier for each node in the form of trainable parameters (different for each node).

**Comment by chenxiaodanhit** [comment]
Thank you for your help!
