### ISSUE TITLE
run bug: takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by maisuiqianxun** [Graph-Machine-Learning-Group/spin#4]
Hi authors, i attempt to run your great imputation algorithm spin, but the TypeError occurs as shown in the following log. Is it caused by the bug in your package "tsl"?

File "/home/user/anaconda3/envs/spin/lib/python3.8/site-packages/tsl/imputers/imputer.py", line 134, in on_train_batch_start
    super(Imputer, self).on_train_batch_start(batch, batch_idx, unused)
TypeError: on_train_batch_start() takes 3 positional arguments but 4 were given.

**Comment by logicalee** [comment]
hi how did you fix it? I meet the same problem

**Comment by maisuiqianxun** [comment]
> hi how did you fix it? I meet the same problem

Hello, I replace the code "super(Imputer, self).on_train_batch_start(batch, batch_idx, unused)" in line 134 with the code "super(Imputer, self).on_train_batch_start(batch, batch_idx)" and it worked. Hope this helps.

**Comment by logicalee** [comment]
> it works.thanks!

**Comment by JeremyChou28** [comment]
> Hi authors, i attempt to run your great imputation algorithm spin, but the TypeError occurs as shown in the following log. Is it caused by the bug in your package "tsl"?
> 
> File "/home/user/anaconda3/envs/spin/lib/python3.8/site-packages/tsl/imputers/imputer.py", line 134, in on_train_batch_start super(Imputer, self).on_train_batch_start(batch, batch_idx, unused) TypeError: on_train_batch_start() takes 3 positional arguments but 4 were given.

Hello, may I ask if you have successfully run through the spin code? I encountered some bugs while configuring the environment. Could you please tell me about the specific versions of the packages in the environment.

**Comment by maisuiqianxun** [comment]
The default python=3.8. Besides, the installed version of pytorch_lightning in my virtual env is pytorch_lightning=1.8.5. Hope it helps you.

**Comment by maisuiqianxun** [comment]
> > Yeah, we successfully run the official spin code following the `readme.md` file. if you encountered some bugs, can you provide the detailed bug logs? @JeremyChou28
> 
> When running these few lines of code,
> 
> ```
>     output = trainer.predict(imputer, dataloaders=dm.test_dataloader(
>         batch_size=args.batch_inference))
>     output = casting.numpy(output)
>     y_hat, y_true, mask = output['y_hat'].squeeze(-1), \
>                           output['y'].squeeze(-1), \
>                           output['mask'].squeeze(-1)
>     check_mae = numpy_metrics.masked_mae(y_hat, y_true, mask)
>     print(f'Test MAE: {check_mae:.2f}')
>     return y_hat
> ```
> 
> the following error occurs：
> 
> ```
>   File "spin-NeurIPS2022/experiments/run_imputation.py", line 310, in <module>
>     run_experiment(args)
>   File "spin-NeurIPS2022/experiments/run_imputation.py", line 297, in run_experiment
>     output = trainer.predict(imputer, dataloaders=dm.test_dataloader(
>   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 865, in predict
>     return call._call_and_handle_interrupt(
>   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
>     return trainer_fn(*args, **kwargs)
>   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 904, in _predict_impl
>     results = self._run(model, ckpt_path=ckpt_path)
>   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
>     results = self._run_stage()
>   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_stage
>     return self.predict_loop.run()
>   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
>     return loop_run(self, *args, **kwargs)
>   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/loops/prediction_loop.py", line 128, in run
>     return self.on_run_end()
>   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/loops/prediction_loop.py", line 200, in on_run_end
>     results = self._on_predict_epoch_end()
>   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/loops/prediction_loop.py", line 358, in _on_predict_epoch_end
>     call._call_lightning_module_hook(trainer, "on_predict_epoch_end")
>   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
>     output = fn(*args, **kwargs)
> TypeError: Predictor.on_predict_epoch_end() missing 1 required positional argument: 'results'
> ```
> 
> Could you help me solve this problem? Thank you.

The default python version is: python=3.8. Besides, the pytorch_lightning version in my envs is :pytorch_lightning=1.8.5. Hope it helps you.

**Comment by maisuiqianxun** [comment]
Yeah, we successfully run the official spin code following the `readme.md` file. if you encountered some bugs,  can you provide the detailed bug logs?
@JeremyChou28

**Comment by JeremyChou28** [comment]
> Yeah, we successfully run the official spin code following the `readme.md` file. if you encountered some bugs, can you provide the detailed bug logs? @JeremyChou28

When running these few lines of code,
```
    output = trainer.predict(imputer, dataloaders=dm.test_dataloader(
        batch_size=args.batch_inference))
    output = casting.numpy(output)
    y_hat, y_true, mask = output['y_hat'].squeeze(-1), \
                          output['y'].squeeze(-1), \
                          output['mask'].squeeze(-1)
    check_mae = numpy_metrics.masked_mae(y_hat, y_true, mask)
    print(f'Test MAE: {check_mae:.2f}')
    return y_hat
```

the following error occurs：
```
  File "spin-NeurIPS2022/experiments/run_imputation.py", line 310, in <module>
    run_experiment(args)
  File "spin-NeurIPS2022/experiments/run_imputation.py", line 297, in run_experiment
    output = trainer.predict(imputer, dataloaders=dm.test_dataloader(
  File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 865, in predict
    return call._call_and_handle_interrupt(
  File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 904, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_stage
    return self.predict_loop.run()
  File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/loops/prediction_loop.py", line 128, in run
    return self.on_run_end()
  File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/loops/prediction_loop.py", line 200, in on_run_end
    results = self._on_predict_epoch_end()
  File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/loops/prediction_loop.py", line 358, in _on_predict_epoch_end
    call._call_lightning_module_hook(trainer, "on_predict_epoch_end")
  File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
TypeError: Predictor.on_predict_epoch_end() missing 1 required positional argument: 'results'
```
Could you help me solve this problem? Thank you.

**Comment by JeremyChou28** [comment]
> > > Yeah, we successfully run the official spin code following the `readme.md` file. if you encountered some bugs, can you provide the detailed bug logs? @JeremyChou28
> > 
> > 
> > When running these few lines of code,
> > ```
> >     output = trainer.predict(imputer, dataloaders=dm.test_dataloader(
> >         batch_size=args.batch_inference))
> >     output = casting.numpy(output)
> >     y_hat, y_true, mask = output['y_hat'].squeeze(-1), \
> >                           output['y'].squeeze(-1), \
> >                           output['mask'].squeeze(-1)
> >     check_mae = numpy_metrics.masked_mae(y_hat, y_true, mask)
> >     print(f'Test MAE: {check_mae:.2f}')
> >     return y_hat
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the following error occurs：
> > ```
> >   File "spin-NeurIPS2022/experiments/run_imputation.py", line 310, in <module>
> >     run_experiment(args)
> >   File "spin-NeurIPS2022/experiments/run_imputation.py", line 297, in run_experiment
> >     output = trainer.predict(imputer, dataloaders=dm.test_dataloader(
> >   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 865, in predict
> >     return call._call_and_handle_interrupt(
> >   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
> >     return trainer_fn(*args, **kwargs)
> >   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 904, in _predict_impl
> >     results = self._run(model, ckpt_path=ckpt_path)
> >   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
> >     results = self._run_stage()
> >   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_stage
> >     return self.predict_loop.run()
> >   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
> >     return loop_run(self, *args, **kwargs)
> >   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/loops/prediction_loop.py", line 128, in run
> >     return self.on_run_end()
> >   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/loops/prediction_loop.py", line 200, in on_run_end
> >     results = self._on_predict_epoch_end()
> >   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/loops/prediction_loop.py", line 358, in _on_predict_epoch_end
> >     call._call_lightning_module_hook(trainer, "on_predict_epoch_end")
> >   File "miniconda3/envs/spin/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
> >     output = fn(*args, **kwargs)
> > TypeError: Predictor.on_predict_epoch_end() missing 1 required positional argument: 'results'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you help me solve this problem? Thank you.
> 
> The default python version is: python=3.8. Besides, the pytorch_lightning version in my envs is :pytorch_lightning=1.8.5. Hope it helps you.

I have resolved this issue. Thank you very much.
