### ISSUE TITLE
Missing Values for AirQuality Dataset

### ISSUE THREAD

**Issue by rjing2525** [Graph-Machine-Learning-Group/spin#7]
Hi, 

To conduct experiments with different missing rates and failure probabilities for the AQI dataset, do you also use the "add_missing_values()" function for the AQI dataset?

**Comment by marshka** [comment]
The AQI dataset has already the masks needed for imputation (`training_mask` and `eval_mask`). In the experiment where we change the masks distribution at inference, we update the masks for all datasets in the same way:

https://github.com/Graph-Machine-Learning-Group/spin/blob/2320695ff03b23606e73b05ac87f3ddff9d74c0c/experiments/run_inference.py#L138-L147

You can do the same if you want to use different masks distributions.
