### ISSUE TITLE
BUG ValueError: Unexpected keyword arguments: `compute_on_step`

### ISSUE THREAD

**Issue by MingxiLii** [Graph-Machine-Learning-Group/spin#9]
envs/spin/lib/python3.8/site-packages/torchmetrics/metric.py", line 146, in __init__
raise ValueError(f"Unexpected keyword arguments: {', '.join(kwargs_)}")

**Comment by marshka** [comment]
Hi, which version of `torchmetrics` are you using?

**Comment by MingxiLii** [comment]
Thanks! This problem has been solved by re-installing torchmetrics 0.8.2. But a new bug shows as follows with pytorch 2.01 and pytorch-lightening 1.5.10:
envs/spin/lib/python3.8/site-packages/pytorch_lightning/trainer/optimizers.py", line 192, in _configure_schedulers
raise ValueError(f'The provided lr scheduler "{scheduler}" is invalid')
ValueError: The provided lr scheduler "<spin.scheduler.CosineSchedulerWithRestarts object at 0x7f3f14ca7df0>" is invalid

**Comment by JeremyChou28** [comment]
I also encountered the same problem. Could you specify the version of the dependent package required to run it. Thank you.
